"use strict";
const MA_PRODUCT_KEY="maMomentsProducts",MA_CART_KEY="maMomentsCart",MA_WISHLIST_KEY="maMomentsWishlist";
const MA_DEFAULT_PRODUCTS=[
{id:"pajama-1",name:"بيجامة قطنية وردية",category:"pajamas",price:85,description:"بيجامة قطنية ناعمة ومريحة للنوم والاستخدام اليومي.",image:"images/categories/pajamas/p1.jpeg",images:["images/categories/pajamas/p1.jpeg"],colors:[{name:"وردي",hex:"#e8a0b6"},{name:"أبيض",hex:"#ffffff"}],sizes:["S","M","L","XL"],material:"قطن",tags:["بيجامة","بيجامات","ملابس نوم","ناعمة","صيفية"],similarTo:["شي إن","زارا"],createdAt:1710000000000},
{id:"pajama-2",name:"بيجامة ساتان سوداء",category:"pajamas",price:120,description:"بيجامة ساتان أنيقة بقصة مريحة ولمعة ناعمة.",image:"images/categories/pajamas/p2.jpeg",images:["images/categories/pajamas/p2.jpeg"],colors:[{name:"أسود",hex:"#111111"}],sizes:["XS","S","M","L"],material:"ساتان",tags:["بيجامة","بيجامات","ملابس نوم","أنيقة"],similarTo:["فيكتوريا سيكريت"],createdAt:1720000000000},
{id:"pajama-3",name:"بيجامة مخططة زرقاء",category:"pajamas",price:95,description:"طقم بيجامة مخطط مريح مناسب للمنزل والنوم.",image:"images/categories/pajamas/p3.jpeg",images:["images/categories/pajamas/p3.jpeg"],colors:[{name:"أزرق",hex:"#5d8fb4"},{name:"أبيض",hex:"#ffffff"}],sizes:["M","L","XL","XXL"],material:"قطن",tags:["بيجامة","بيجامات","مخططة"],similarTo:["زارا هوم"],createdAt:1730000000000},
{id:"pajama-4",name:"بيجامة شتوية بيج",category:"pajamas",price:140,description:"بيجامة دافئة وناعمة للأيام الباردة.",image:"images/categories/pajamas/p4.jpeg",images:["images/categories/pajamas/p4.jpeg"],colors:[{name:"بيج",hex:"#d8c2a8"},{name:"بني",hex:"#795548"}],sizes:["S","M","L","XL","XXL"],material:"فليس",tags:["بيجامة","بيجامات","شتوية"],similarTo:["H&M"],createdAt:1740000000000},
{id:"pajama-5",name:"بيجامة منزلية حمراء",category:"pajamas",price:105,description:"بيجامة نسائية مريحة بلون أحمر وتصميم عملي.",image:"images/categories/pajamas/p5.jpeg",images:["images/categories/pajamas/p5.jpeg"],colors:[{name:"أحمر",hex:"#b33a3a"}],sizes:["XS","S","M","L","XL","XXL"],material:"قطن",tags:["بيجامة","بيجامات","نسائية"],similarTo:["شي إن"],createdAt:1750000000000}
];
const MA_CATEGORY_NAMES={pajamas:"بيجامات","work-sets":"أطقم عملية","plus-size":"مقاسات كبيرة",beauty:"تجميل",cups:"أكواب",candles:"شموع",stationery:"مستلزمات مكتبية","happiness-boxes":"بوكسات السعادة"};
function maNormalize(v=""){return String(v).toLowerCase().trim().replace(/[أإآٱ]/g,"ا").replace(/ة/g,"ه").replace(/ى/g,"ي").replace(/[ًٌٍَُِّْـ]/g,"").replace(/[^\u0600-\u06FFa-z0-9+\-\s]/gi," ").replace(/\s+/g," ").trim()}
function maNormalizeProduct(p){const colors=(p.colors||[]).map(c=>typeof c==="string"?{name:c,hex:"#c9a98c"}:c);const images=Array.isArray(p.images)&&p.images.length?p.images:[p.image].filter(Boolean);return {...p,status:p.status||"active",stock:Number(p.stock||0),featured:!!p.featured,showOnHomepage:!!p.showOnHomepage,colors,images,image:images[0]||p.image};}
function maGetProducts(){try{const s=JSON.parse(localStorage.getItem(MA_PRODUCT_KEY)||"null");if(Array.isArray(s))return s.map(maNormalizeProduct)}catch(_){} maSaveProducts(MA_DEFAULT_PRODUCTS);return MA_DEFAULT_PRODUCTS.map(maNormalizeProduct)}
function maSaveProducts(p){localStorage.setItem(MA_PRODUCT_KEY,JSON.stringify(p.map(maNormalizeProduct)));window.dispatchEvent(new CustomEvent("ma-products-updated"))}
function maGetArray(k){try{const v=JSON.parse(localStorage.getItem(k)||"[]");return Array.isArray(v)?v:[]}catch(_){return[]}}
function maSetArray(k,v){localStorage.setItem(k,JSON.stringify(v));window.dispatchEvent(new CustomEvent("ma-data-updated"))}
function maAddToWishlist(product){let w=maGetArray(MA_WISHLIST_KEY);const i=w.findIndex(x=>x.id===product.id);if(i>=0)w.splice(i,1);else w.push(maNormalizeProduct(product));maSetArray(MA_WISHLIST_KEY,w);return i<0}
function maAddToCart(product,size="",color=""){const cName=typeof color==="string"?color:(color?.name||"");let cart=maGetArray(MA_CART_KEY),key=`${product.id}-${size}-${cName}`,e=cart.find(x=>x.key===key);if(e)e.quantity=(e.quantity||1)+1;else cart.push({...maNormalizeProduct(product),key,selectedSize:size,selectedColor:cName,quantity:1});maSetArray(MA_CART_KEY,cart)}
function maSmartSearch(products,q){const words=maNormalize(q).split(" ").filter(Boolean).map(w=>["بيجامه","بيجامات","بجامه","بجامات"].includes(w)?"بيجام":w);return products.map(product=>{const text=maNormalize([product.name,product.description,MA_CATEGORY_NAMES[product.category],product.material,...(product.colors||[]).map(c=>c.name),...(product.sizes||[]),...(product.tags||[]),...(product.similarTo||[])].join(" ")).replace(/بيجامات|بيجامه|بجامات|بجامه/g,"بيجام");let score=0;words.forEach(w=>{if(["بديل","شبيه","مشابه","dupe"].includes(w))score+=1;else if(text.includes(w))score+=10});return{product,score}}).filter(r=>r.score>=Math.max(1,words.filter(w=>!["بديل","شبيه","مشابه","dupe"].includes(w)).length*10)).sort((a,b)=>b.score-a.score||b.product.createdAt-a.product.createdAt)}
function maColorHex(name){const n=maNormalize(name),m={وردي:"#e8a0b6",زهري:"#e8a0b6",اسود:"#111111",ابيض:"#ffffff",ازرق:"#5d8fb4",احمر:"#b33a3a",بيج:"#d8c2a8",بني:"#795548",اخضر:"#5c8d63",بنفسجي:"#8b6aa8",رمادي:"#888888"};return m[n]||"#c9a98c"}

function maHeartIcon(active=false){return `<svg class="heart-svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78L12 21.23l8.84-8.84a5.5 5.5 0 0 0 0-7.78Z"></path></svg>`}
